import json
import subprocess
import sys
from pathlib import Path

from fastapi.testclient import TestClient

from app.llm.config import LLMConfig
from app.main import create_app
from app.services.telegram_service import TelegramConfig
from app.webhooks import WebhookConfig, normalize_trade_signal_payload


WEBHOOK_PAYLOAD = {
    "source": "external_penny_bot",
    "signal_id": "sig_20260630_001",
    "ticker": "ABCD",
    "strategy_signal": "breakout",
    "side": "buy",
    "price": 0.82,
    "volume": 12_500_000,
    "timeframe": "1m",
    "timestamp": "2026-06-30T09:35:00Z",
    "technical_indicators": {
        "rsi": 68,
        "vwap_distance": 0.04,
        "relative_volume": 5.2,
    },
    "news_headlines": [],
    "risk_context": {
        "spread_pct": 4.5,
        "float_rotation": 2.1,
        "premarket": True,
    },
    "notes": "candidate generated by external bot",
}


def _webhook_client(tmp_path, *, enabled=True, secret="test-secret", require_secret=True):
    app = create_app(
        db_path=tmp_path / "ai_council.sqlite",
        report_dir=tmp_path / "reports",
        upload_root=tmp_path / "uploads",
        llm_config=LLMConfig(provider="mock"),
        telegram_config=TelegramConfig(enabled=False),
        webhook_config=WebhookConfig(
            enabled=enabled,
            secret=secret,
            require_secret=require_secret,
        ),
    )
    return TestClient(app)


def _secret_headers(secret="test-secret"):
    return {"X-AI-Council-Webhook-Secret": secret}


def test_webhooks_disabled_returns_safe_response(client):
    response = client.post("/api/webhooks/trade-signal", json=WEBHOOK_PAYLOAD)

    assert response.status_code == 503
    payload = response.json()
    assert payload["status"] == "disabled"
    assert payload["order_execution_allowed"] is False


def test_webhook_status_includes_safe_metadata_without_secret(tmp_path):
    with _webhook_client(tmp_path, enabled=True, secret="very-secret", require_secret=True) as client:
        response = client.get("/api/webhooks/status")

    assert response.status_code == 200
    payload = response.json()
    assert payload["endpoint_path"] == "/api/webhooks/trade-signal"
    assert payload["normalize_preview_endpoint_path"] == "/api/webhooks/normalize-preview"
    assert payload["secret_configured"] is True
    assert payload["order_execution_allowed"] is False
    assert "AI Council does not execute trades or connect to broker APIs" in payload["safety_boundary"]
    assert "very-secret" not in json.dumps(payload)


def test_webhooks_missing_configured_secret_is_disabled(tmp_path):
    with _webhook_client(tmp_path, enabled=True, secret=None, require_secret=True) as client:
        status_response = client.get("/api/webhooks/status")
        post_response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    assert status_response.status_code == 200
    assert status_response.json()["configured"] is False
    assert status_response.json()["missing"] == ["WEBHOOK_SECRET"]
    assert post_response.status_code == 503
    assert post_response.json()["status"] == "disabled"


def test_missing_secret_returns_401_when_required(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post("/api/webhooks/trade-signal", json=WEBHOOK_PAYLOAD)

    assert response.status_code == 401


def test_wrong_secret_returns_401(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers("wrong-secret"),
        )

    assert response.status_code == 401


def test_valid_secret_creates_trade_review(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    assert response.status_code == 201
    payload = response.json()
    assert payload["status"] == "reviewed"
    assert payload["duplicated"] is False
    assert payload["event"]["status"] == "reviewed"
    assert payload["trade_review"]["ticker"] == "ABCD"
    assert payload["trade_review"]["side"] == "review_only"
    assert payload["trade_review"]["input_payload"]["raw_side"] == "buy"
    assert payload["order_execution_allowed"] is False
    assert payload["structured_decision"]["order_execution_allowed"] is False


def test_webhook_event_preserves_raw_and_normalized_payload(tmp_path):
    payload = {
        **WEBHOOK_PAYLOAD,
        "signal_id": "sig_raw_payload",
        "symbol": "TESTA",
        "quantity": 1000,
    }
    payload.pop("ticker")
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=payload,
            headers=_secret_headers(),
        )
        event_id = response.json()["event"]["id"]
        detail = client.get(f"/api/webhooks/events/{event_id}")

    assert response.status_code == 201
    event = detail.json()["event"]
    assert event["raw_payload"]["symbol"] == "TESTA"
    assert event["raw_payload"]["quantity"] == 1000
    assert event["normalized_payload"]["ticker"] == "TESTA"
    assert event["normalized_payload"]["side"] == "review_only"
    assert event["normalized_payload"]["input_payload_json"]["quantity"] == 1000
    assert event["order_execution_allowed"] is False


def test_alias_payload_normalization():
    normalized = normalize_trade_signal_payload(
        {
            "source": "alias_bot",
            "signal_id": "sig_alias",
            "symbol": "xyz",
            "setup": "gap_break",
            "code": "xyz",
            "pattern": "gap_break",
            "action": "sell",
            "current_price": "1.23",
            "day_volume": "900000",
            "tf": "5m",
            "event_time": "2026-06-30T10:00:00Z",
            "ta": {"rsi": 72},
            "catalysts": [{"title": "Filed 8-K"}],
            "meta": {"spread_pct": 2.5},
        }
    )

    assert normalized["ticker"] == "XYZ"
    assert normalized["strategy_signal"] == "gap_break"
    assert normalized["side"] == "review_only"
    assert normalized["raw_side"] == "sell"
    assert normalized["price"] == 1.23
    assert normalized["volume"] == 900000
    assert normalized["timeframe"] == "5m"
    assert normalized["technical_indicators"] == {"rsi": 72}
    assert normalized["news_headlines"] == ["Filed 8-K"]
    assert normalized["risk_context"]["event_time"] == "2026-06-30T10:00:00Z"
    assert normalized["risk_context"]["raw_side"] == "sell"
    assert any("review context only" in warning for warning in normalized["adapter_warnings"])
    assert normalized["order_execution_allowed"] is False


def test_order_like_fields_are_ignored_with_warning():
    payload = {
        "source": "compat_bot",
        "signal_id": "order_like_001",
        "instrument": "TESTD",
        "trigger": "halt_watch",
        "intent": "entry",
        "trigger_price": 0.29,
        "vol": 620000,
        "headlines": [],
        "quantity": 5000,
        "order_type": "limit",
        "stop_loss": 0.22,
    }

    normalized = normalize_trade_signal_payload(payload)

    assert normalized["side"] == "review_only"
    assert normalized["raw_side"] == "entry"
    assert normalized["input_payload_json"]["quantity"] == 5000
    warnings = " ".join(normalized["adapter_warnings"])
    assert "order-like fields ignored for safety" in warnings
    assert "quantity" in warnings
    assert "order_type" in warnings
    assert "stop_loss" in warnings
    assert normalized["order_execution_allowed"] is False


def test_us_trader_oracle_alias_normalization_with_profile_wrapper():
    payload_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "sample_payloads"
    )
    raw_payload = json.loads(
        (payload_dir / "us_trader_oracle_signal.json").read_text(encoding="utf-8")
    )

    normalized = normalize_trade_signal_payload(
        {"profile": "us_trader_oracle_v1", "payload": raw_payload}
    )

    assert normalized["ticker"] == "TESTA"
    assert normalized["strategy_signal"] == "breakout"
    assert normalized["side"] == "review_only"
    assert normalized["raw_side"] == "buy"
    assert normalized["source"] == "us_trader_oracle"
    assert normalized["risk_context"]["bridge_profile"] == "us_trader_oracle_v1"
    assert normalized["input_payload_json"]["payload"]["symbol"] == "TESTA"
    assert any("review context only" in warning for warning in normalized["adapter_warnings"])
    assert normalized["order_execution_allowed"] is False


def test_us_trader_oracle_order_like_fields_are_warned_and_not_normalized_as_orders():
    payload_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "sample_payloads"
    )
    raw_payload = json.loads(
        (payload_dir / "us_trader_oracle_order_like_signal.json").read_text(encoding="utf-8")
    )

    normalized = normalize_trade_signal_payload(
        {"profile": "us_trader_oracle_v1", "payload": raw_payload}
    )

    assert normalized["side"] == "review_only"
    assert normalized["raw_side"] == "buy"
    warning_text = " ".join(normalized["adapter_warnings"])
    assert "order-like fields ignored for safety" in warning_text
    assert "quantity" in warning_text
    assert "order_type" in warning_text
    assert "stop_loss" in warning_text
    assert "take_profit" in warning_text
    assert normalized["order_execution_allowed"] is False


def test_normalize_preview_does_not_create_trade_review(tmp_path):
    payload = {**WEBHOOK_PAYLOAD, "signal_id": "preview_only"}
    with _webhook_client(tmp_path, enabled=False, secret=None) as client:
        response = client.post("/api/webhooks/normalize-preview", json=payload)
        reviews = client.get("/api/trade-reviews")
        events = client.get("/api/webhooks/events")

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "preview"
    assert body["trade_review_created"] is False
    assert body["created_trade_review"] is False
    assert body["normalized_payload"]["side"] == "review_only"
    assert body["normalized_payload"]["raw_side"] == "buy"
    assert reviews.json() == []
    assert events.json() == []
    assert body["order_execution_allowed"] is False


def test_us_trader_oracle_normalize_preview_does_not_create_trade_review(tmp_path):
    payload_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "sample_payloads"
    )
    raw_payload = json.loads(
        (payload_dir / "us_trader_oracle_signal.json").read_text(encoding="utf-8")
    )
    with _webhook_client(tmp_path, enabled=False, secret=None) as client:
        response = client.post(
            "/api/webhooks/normalize-preview",
            json={"profile": "us_trader_oracle_v1", "payload": raw_payload},
        )
        reviews = client.get("/api/trade-reviews")

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "preview"
    assert body["trade_review_created"] is False
    assert body["created_trade_review"] is False
    assert body["normalized_payload"]["ticker"] == "TESTA"
    assert body["normalized_payload"]["side"] == "review_only"
    assert body["normalized_payload"]["raw_side"] == "buy"
    assert reviews.json() == []
    assert body["order_execution_allowed"] is False


def test_missing_ticker_validation_returns_adapter_warning(tmp_path):
    payload = {**WEBHOOK_PAYLOAD}
    payload.pop("ticker")
    payload.pop("symbol", None)
    with _webhook_client(tmp_path, enabled=False, secret=None) as client:
        response = client.post("/api/webhooks/normalize-preview", json=payload)

    assert response.status_code == 422
    body = response.json()
    assert body["status"] == "rejected"
    assert "missing ticker" in body["adapter_warnings"]
    assert body["order_execution_allowed"] is False


def test_sample_payloads_are_valid_json_and_normalize_successfully():
    payload_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "sample_payloads"
    )
    expected = {
        "breakout_signal.json",
        "high_spread_signal.json",
        "missing_news_signal.json",
        "duplicate_signal.json",
        "generic_bot_signal.json",
        "penny_bot_v1_signal.json",
        "order_like_fields_signal.json",
        "minimal_signal.json",
        "us_trader_oracle_signal.json",
        "us_trader_oracle_order_like_signal.json",
        "us_trader_oracle_minimal_signal.json",
        "us_trader_oracle_high_risk_signal.json",
    }
    found = {path.name for path in payload_dir.glob("*.json")}
    assert found >= expected
    for path in payload_dir.glob("*.json"):
        payload = json.loads(path.read_text(encoding="utf-8"))
        normalized = normalize_trade_signal_payload(payload)
        assert normalized["ticker"].startswith("TEST")
        assert normalized["strategy_signal"]
        assert normalized["order_execution_allowed"] is False


def test_bridge_mapping_profiles_are_valid_json():
    profile_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "mapping_profiles"
    )
    expected = {
        "generic.json",
        "penny_bot_v1.json",
        "minimal_signal.json",
        "us_trader_oracle_v1.json",
    }
    found = {path.name for path in profile_dir.glob("*.json")}
    assert found >= expected
    for path in profile_dir.glob("*.json"):
        profile = json.loads(path.read_text(encoding="utf-8"))
        assert isinstance(profile["fields"], dict)
        assert "ticker" in profile["fields"]
        assert "strategy_signal" in profile["fields"]


def test_us_trader_oracle_profile_json_validation():
    profile_path = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "mapping_profiles"
        / "us_trader_oracle_v1.json"
    )
    profile = json.loads(profile_path.read_text(encoding="utf-8"))

    assert profile["name"] == "us_trader_oracle_v1"
    assert profile["source"] == "us_trader_oracle"
    assert "symbol" in profile["fields"]["ticker"]
    assert "action" in profile["fields"]["side"]
    assert "quantity" in profile["order_like_fields"]
    assert profile["safety_policy"]["order_execution_allowed"] is False


def test_bridge_client_dry_run_sample_payload():
    root = Path(__file__).resolve().parents[2]
    script = root / "examples" / "external_bot" / "bridge_client.py"
    payload = root / "examples" / "external_bot" / "sample_payloads" / "order_like_fields_signal.json"
    result = subprocess.run(
        [
            sys.executable,
            str(script),
            "--payload",
            str(payload),
            "--profile",
            "generic",
            "--dry-run",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    body = json.loads(result.stdout)
    assert body["status"] == "dry_run"
    assert body["webhook_called"] is False
    assert body["normalized_preview"]["ticker"] == "TESTD"
    assert body["normalized_preview"]["side"] == "review_only"
    assert body["normalized_preview"]["order_execution_allowed"] is False
    assert any(
        "order-like fields ignored for safety" in warning
        for warning in body["normalized_preview"]["adapter_warnings"]
    )


def test_us_trader_oracle_bridge_dry_run_sample_payload():
    root = Path(__file__).resolve().parents[2]
    script = root / "examples" / "external_bot" / "us_trader_oracle_bridge.py"
    payload = (
        root
        / "examples"
        / "external_bot"
        / "sample_payloads"
        / "us_trader_oracle_order_like_signal.json"
    )
    result = subprocess.run(
        [
            sys.executable,
            str(script),
            "--payload",
            str(payload),
            "--profile",
            "us_trader_oracle_v1",
            "--dry-run",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    body = json.loads(result.stdout)
    assert body["status"] == "dry_run"
    assert body["webhook_called"] is False
    assert body["broker_api_called"] is False
    assert body["normalized_preview"]["ticker"] == "TESTB"
    assert body["normalized_preview"]["side"] == "review_only"
    assert body["normalized_preview"]["raw_side"] == "buy"
    assert body["normalized_preview"]["order_execution_allowed"] is False
    assert any(
        "order-like fields ignored for safety" in warning
        for warning in body["normalized_preview"]["adapter_warnings"]
    )


def test_us_trader_oracle_smoke_script_exists():
    root = Path(__file__).resolve().parents[2]
    assert (root / "examples" / "integration" / "run_us_trader_oracle_bridge_smoke.py").exists()
    assert (root / "scripts" / "run_us_trader_oracle_bridge_smoke.sh").exists()


def test_duplicate_sample_payload_returns_existing_review(tmp_path):
    payload_dir = (
        Path(__file__).resolve().parents[2]
        / "examples"
        / "external_bot"
        / "sample_payloads"
    )
    breakout = json.loads((payload_dir / "breakout_signal.json").read_text(encoding="utf-8"))
    duplicate = json.loads((payload_dir / "duplicate_signal.json").read_text(encoding="utf-8"))

    with _webhook_client(tmp_path) as client:
        first = client.post(
            "/api/webhooks/trade-signal",
            json=breakout,
            headers=_secret_headers(),
        )
        second = client.post(
            "/api/webhooks/trade-signal",
            json=duplicate,
            headers=_secret_headers(),
        )

    assert first.status_code == 201
    assert second.status_code == 200
    assert second.json()["duplicated"] is True
    assert second.json()["trade_review"]["id"] == first.json()["trade_review"]["id"]


def test_duplicate_source_signal_id_returns_existing_review(tmp_path):
    with _webhook_client(tmp_path) as client:
        first = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        second = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        events = client.get("/api/webhooks/events")

    assert first.status_code == 201
    assert second.status_code == 200
    assert second.json()["duplicated"] is True
    assert second.json()["trade_review"]["id"] == first.json()["trade_review"]["id"]
    assert len(events.json()) == 1


def test_webhook_order_execution_allowed_always_false(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    payload = response.json()
    assert payload["order_execution_allowed"] is False
    assert payload["trade_review"]["order_execution_allowed"] is False
    assert payload["structured_decision"]["order_execution_allowed"] is False


def test_buy_sell_side_treated_as_review_context_only(tmp_path):
    payload = {**WEBHOOK_PAYLOAD, "side": "sell", "signal_id": "sig_sell_context"}
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=payload,
            headers=_secret_headers(),
        )

    decision = response.json()["structured_decision"]
    assert response.json()["trade_review"]["side"] == "review_only"
    assert response.json()["trade_review"]["input_payload"]["raw_side"] == "sell"
    assert "execution_language_treated_as_review_context" in decision["risk_flags"]
    assert decision["trade_allowed"] is False


def test_webhook_event_list_and_get(tmp_path):
    with _webhook_client(tmp_path) as client:
        created = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        event_id = created.json()["event"]["id"]
        list_response = client.get("/api/webhooks/events")
        detail_response = client.get(f"/api/webhooks/events/{event_id}")

    assert list_response.status_code == 200
    assert any(event["id"] == event_id for event in list_response.json())
    assert detail_response.status_code == 200
    assert detail_response.json()["event"]["id"] == event_id
    assert detail_response.json()["order_execution_allowed"] is False


def test_webhook_telegram_disabled_safe_handling(tmp_path):
    payload = {**WEBHOOK_PAYLOAD, "auto_send_telegram": True, "signal_id": "sig_telegram"}
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=payload,
            headers=_secret_headers(),
        )

    assert response.status_code == 201
    telegram = response.json()["telegram"]
    assert telegram["sent"] is False
    assert telegram["status"] == "disabled"
    assert "Order execution allowed: false" in telegram["message"]


def test_webhook_code_does_not_add_broker_or_order_execution():
    root = Path(__file__).resolve().parents[1] / "app"
    source = "\n".join(path.read_text(encoding="utf-8") for path in root.rglob("*.py"))
    forbidden_terms = [
        "submit_order",
        "place_order",
        "BrokerClient",
        "OrderRequest",
        "TradingClient",
        "tradeapi.REST",
    ]
    for term in forbidden_terms:
        assert term not in source
