from pathlib import Path

from fastapi.testclient import TestClient

from app.llm.config import LLMConfig
from app.main import create_app
from app.services.telegram_service import TelegramConfig
from app.webhooks import WebhookConfig, normalize_trade_signal_payload


WEBHOOK_PAYLOAD = {
    "source": "external_penny_bot",
    "signal_id": "sig_20260630_001",
    "ticker": "ABCD",
    "strategy_signal": "breakout",
    "side": "buy",
    "price": 0.82,
    "volume": 12_500_000,
    "timeframe": "1m",
    "timestamp": "2026-06-30T09:35:00Z",
    "technical_indicators": {
        "rsi": 68,
        "vwap_distance": 0.04,
        "relative_volume": 5.2,
    },
    "news_headlines": [],
    "risk_context": {
        "spread_pct": 4.5,
        "float_rotation": 2.1,
        "premarket": True,
    },
    "notes": "candidate generated by external bot",
}


def _webhook_client(tmp_path, *, enabled=True, secret="test-secret", require_secret=True):
    app = create_app(
        db_path=tmp_path / "ai_council.sqlite",
        report_dir=tmp_path / "reports",
        upload_root=tmp_path / "uploads",
        llm_config=LLMConfig(provider="mock"),
        telegram_config=TelegramConfig(enabled=False),
        webhook_config=WebhookConfig(
            enabled=enabled,
            secret=secret,
            require_secret=require_secret,
        ),
    )
    return TestClient(app)


def _secret_headers(secret="test-secret"):
    return {"X-AI-Council-Webhook-Secret": secret}


def test_webhooks_disabled_returns_safe_response(client):
    response = client.post("/api/webhooks/trade-signal", json=WEBHOOK_PAYLOAD)

    assert response.status_code == 503
    payload = response.json()
    assert payload["status"] == "disabled"
    assert payload["order_execution_allowed"] is False


def test_webhooks_missing_configured_secret_is_disabled(tmp_path):
    with _webhook_client(tmp_path, enabled=True, secret=None, require_secret=True) as client:
        status_response = client.get("/api/webhooks/status")
        post_response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    assert status_response.status_code == 200
    assert status_response.json()["configured"] is False
    assert status_response.json()["missing"] == ["WEBHOOK_SECRET"]
    assert post_response.status_code == 503
    assert post_response.json()["status"] == "disabled"


def test_missing_secret_returns_401_when_required(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post("/api/webhooks/trade-signal", json=WEBHOOK_PAYLOAD)

    assert response.status_code == 401


def test_wrong_secret_returns_401(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers("wrong-secret"),
        )

    assert response.status_code == 401


def test_valid_secret_creates_trade_review(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    assert response.status_code == 201
    payload = response.json()
    assert payload["status"] == "reviewed"
    assert payload["duplicated"] is False
    assert payload["event"]["status"] == "reviewed"
    assert payload["trade_review"]["ticker"] == "ABCD"
    assert payload["trade_review"]["side"] == "buy"
    assert payload["order_execution_allowed"] is False
    assert payload["structured_decision"]["order_execution_allowed"] is False


def test_alias_payload_normalization():
    normalized = normalize_trade_signal_payload(
        {
            "source": "alias_bot",
            "signal_id": "sig_alias",
            "symbol": "xyz",
            "setup": "gap_break",
            "side": "sell",
            "last_price": "1.23",
            "current_volume": "900000",
            "interval": "5m",
            "event_time": "2026-06-30T10:00:00Z",
            "indicators": {"rsi": 72},
            "headlines": ["Filed 8-K"],
            "risk": {"spread_pct": 2.5},
        }
    )

    assert normalized["ticker"] == "XYZ"
    assert normalized["strategy_signal"] == "gap_break"
    assert normalized["side"] == "sell"
    assert normalized["price"] == 1.23
    assert normalized["volume"] == 900000
    assert normalized["timeframe"] == "5m"
    assert normalized["technical_indicators"] == {"rsi": 72}
    assert normalized["news_headlines"] == ["Filed 8-K"]
    assert normalized["risk_context"]["event_time"] == "2026-06-30T10:00:00Z"
    assert normalized["order_execution_allowed"] is False


def test_duplicate_source_signal_id_returns_existing_review(tmp_path):
    with _webhook_client(tmp_path) as client:
        first = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        second = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        events = client.get("/api/webhooks/events")

    assert first.status_code == 201
    assert second.status_code == 200
    assert second.json()["duplicated"] is True
    assert second.json()["trade_review"]["id"] == first.json()["trade_review"]["id"]
    assert len(events.json()) == 1


def test_webhook_order_execution_allowed_always_false(tmp_path):
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )

    payload = response.json()
    assert payload["order_execution_allowed"] is False
    assert payload["trade_review"]["order_execution_allowed"] is False
    assert payload["structured_decision"]["order_execution_allowed"] is False


def test_buy_sell_side_treated_as_review_context_only(tmp_path):
    payload = {**WEBHOOK_PAYLOAD, "side": "sell", "signal_id": "sig_sell_context"}
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=payload,
            headers=_secret_headers(),
        )

    decision = response.json()["structured_decision"]
    assert response.json()["trade_review"]["side"] == "sell"
    assert "execution_language_treated_as_review_context" in decision["risk_flags"]
    assert decision["trade_allowed"] is False


def test_webhook_event_list_and_get(tmp_path):
    with _webhook_client(tmp_path) as client:
        created = client.post(
            "/api/webhooks/trade-signal",
            json=WEBHOOK_PAYLOAD,
            headers=_secret_headers(),
        )
        event_id = created.json()["event"]["id"]
        list_response = client.get("/api/webhooks/events")
        detail_response = client.get(f"/api/webhooks/events/{event_id}")

    assert list_response.status_code == 200
    assert any(event["id"] == event_id for event in list_response.json())
    assert detail_response.status_code == 200
    assert detail_response.json()["event"]["id"] == event_id
    assert detail_response.json()["order_execution_allowed"] is False


def test_webhook_telegram_disabled_safe_handling(tmp_path):
    payload = {**WEBHOOK_PAYLOAD, "auto_send_telegram": True, "signal_id": "sig_telegram"}
    with _webhook_client(tmp_path) as client:
        response = client.post(
            "/api/webhooks/trade-signal",
            json=payload,
            headers=_secret_headers(),
        )

    assert response.status_code == 201
    telegram = response.json()["telegram"]
    assert telegram["sent"] is False
    assert telegram["status"] == "disabled"
    assert "Order execution allowed: false" in telegram["message"]


def test_webhook_code_does_not_add_broker_or_order_execution():
    root = Path(__file__).resolve().parents[1] / "app"
    source = "\n".join(path.read_text(encoding="utf-8") for path in root.rglob("*.py"))
    forbidden_terms = [
        "submit_order",
        "place_order",
        "BrokerClient",
        "OrderRequest",
        "TradingClient",
        "tradeapi.REST",
    ]
    for term in forbidden_terms:
        assert term not in source
