from pathlib import Path


TRADE_REVIEW_PAYLOAD = {
    "ticker": "ABCD",
    "strategy_signal": "breakout",
    "side": "watch_only",
    "price": 0.82,
    "volume": 12_500_000,
    "timeframe": "1m",
    "source": "external_bot",
    "notes": "candidate signal generated by existing bot",
    "technical_indicators": {
        "rsi": 68,
        "vwap_distance": 0.04,
    },
    "news_headlines": [],
    "risk_context": {
        "spread_pct": 4.5,
        "float_rotation": 2.1,
        "premarket": True,
    },
}


def test_trade_review_create(client):
    response = client.post("/api/trade-reviews", json=TRADE_REVIEW_PAYLOAD)

    assert response.status_code == 201
    payload = response.json()
    review = payload["trade_review"]
    assert review["ticker"] == "ABCD"
    assert review["strategy_signal"] == "breakout"
    assert review["side"] == "watch_only"
    assert review["linked_meeting_id"]
    assert payload["meeting"]["mode"] == "risk_gate_review"
    assert payload["order_execution_allowed"] is False


def test_trade_review_response_includes_structured_decision(client):
    response = client.post("/api/trade-reviews", json=TRADE_REVIEW_PAYLOAD)

    assert response.status_code == 201
    decision = response.json()["structured_decision"]
    assert set(decision) >= {
        "decision",
        "confidence",
        "risk_level",
        "trade_allowed",
        "position_size_multiplier",
        "primary_reasons",
        "risk_flags",
        "required_follow_up",
        "data_quality",
        "order_execution_allowed",
    }
    assert decision["order_execution_allowed"] is False
    assert decision["trade_allowed"] is False


def test_trade_review_order_execution_allowed_always_false_for_execution_language(client):
    payload = {**TRADE_REVIEW_PAYLOAD, "side": "buy"}

    response = client.post("/api/trade-reviews", json=payload)

    assert response.status_code == 201
    body = response.json()
    decision = body["structured_decision"]
    assert body["trade_review"]["side"] == "buy"
    assert decision["order_execution_allowed"] is False
    assert body["trade_review"]["order_execution_allowed"] is False
    assert "execution_language_treated_as_review_context" in decision["risk_flags"]


def test_high_spread_trade_review_is_hold_or_block(client):
    payload = {
        **TRADE_REVIEW_PAYLOAD,
        "risk_context": {
            "spread_pct": 4.5,
            "premarket": False,
        },
    }

    response = client.post("/api/trade-reviews", json=payload)

    assert response.status_code == 201
    decision = response.json()["structured_decision"]
    assert decision["decision"] in {"HOLD", "BLOCK"}
    assert decision["risk_level"] in {"high", "critical"}
    assert "high_spread_risk" in decision["risk_flags"]
    assert decision["trade_allowed"] is False


def test_missing_news_sets_limited_data_quality(client):
    response = client.post("/api/trade-reviews", json=TRADE_REVIEW_PAYLOAD)

    assert response.status_code == 201
    decision = response.json()["structured_decision"]
    assert decision["data_quality"] == "limited"
    assert "missing_news_context" in decision["risk_flags"]
    assert any("validated news" in item for item in decision["required_follow_up"])


def test_trade_review_list_and_get(client):
    created = client.post("/api/trade-reviews", json=TRADE_REVIEW_PAYLOAD)
    assert created.status_code == 201
    review_id = created.json()["trade_review"]["id"]

    list_response = client.get("/api/trade-reviews")
    detail_response = client.get(f"/api/trade-reviews/{review_id}")

    assert list_response.status_code == 200
    assert any(review["id"] == review_id for review in list_response.json())
    assert detail_response.status_code == 200
    assert detail_response.json()["trade_review"]["id"] == review_id
    assert detail_response.json()["order_execution_allowed"] is False


def test_trade_review_telegram_disabled_send(client):
    created = client.post("/api/trade-reviews", json=TRADE_REVIEW_PAYLOAD)
    assert created.status_code == 201
    review_id = created.json()["trade_review"]["id"]

    response = client.post(f"/api/trade-reviews/{review_id}/telegram/send")

    assert response.status_code == 200
    payload = response.json()
    assert payload["sent"] is False
    assert payload["status"] == "disabled"
    assert "Order execution allowed: false" in payload["message"]


def test_trade_review_code_does_not_add_broker_or_order_execution():
    root = Path(__file__).resolve().parents[1] / "app"
    source = "\n".join(path.read_text(encoding="utf-8") for path in root.rglob("*.py"))
    forbidden_terms = [
        "submit_order",
        "place_order",
        "BrokerClient",
        "OrderRequest",
        "TradingClient",
        "tradeapi.REST",
    ]
    for term in forbidden_terms:
        assert term not in source
